feature: docs for wt-search-bar and wt-hint updated  [WTEL-3766]
webitel/webitel-ui-docs pull request #21
Opened 2023-09-19 12:49 UTC by VladimirBeria

2023-09-19 12:58 UTC, liza-pohranichna commented on src/components/pages/webitel-ui/components/wt-search-bar/wt-search-bar-docs.vue
> +          v-model="value"
звикла бачити v-model першим в списку))

2023-09-19 14:28 UTC, liza-pohranichna approved these changes

2023-09-19 14:30 UTC, dlohvinov requested changes

2023-09-19 14:30 UTC, dlohvinov commented on src/components/pages/webitel-ui/components/wt-hint/wt-hint-docs.vue
> +          code: '<wt-hint :iconColor="iconColor"></wt-hint>',
пропси -- кебаб кейсом

2023-09-19 14:30 UTC, dlohvinov commented on src/components/pages/webitel-ui/components/wt-search-bar/wt-search-bar-docs.vue
> +          code: '<wt-search-bar :custom-validators="cronValidator"></wt-search-bar>',
кастом валідаторс хоче масив, а тут передано в код прикладі об'єкт

2023-09-20 08:50 UTC, dlohvinov requested changes

2023-09-20 08:50 UTC, dlohvinov commented on src/components/pages/webitel-ui/components/wt-search-bar/wt-search-bar-docs.vue
> +          code: '<wt-search-bar :custom-validators="[{ name: \'cron\', text: this.$t(\'validation.cron\') }]"></wt-search-bar>',
думаєш, це працюватиме?
треба передати сам валідатор
це не треба писати тут, а треба було просто те що було спочатку обгорнути у масив: `:custom=[customV]`

2023-09-20 08:50 UTC, dlohvinov commented on src/components/pages/webitel-ui/components/wt-search-bar/wt-search-bar-docs.vue
> +          scope: [{ name: 'invalid' }],
а крім нейма там же і велью напевне ще є?)
і можна описати, що то за інвалід?)

2023-09-21 13:58 UTC, dlohvinov approved these changes

2023-09-21 13:58 UTC, merged